DEF MAX_BENCH_POKEMON     EQU 5
DEF MAX_PLAY_AREA_POKEMON EQU 6 ; active + bench
DEF MAX_HP                EQU 120
DEF HP_BAR_LENGTH         EQU MAX_HP / 10

DEF STARTING_HAND_SIZE EQU 7

; coin result constants
DEF TAILS EQU 0
DEF HEADS EQU 1

; hWhoseTurn constants
DEF PLAYER_TURN   EQUS "HIGH(wPlayerDuelVariables)"
DEF OPPONENT_TURN EQUS "HIGH(wOpponentDuelVariables)"

; wDuelFinished constants
DEF DUEL_NOT_FINISHED EQU $0
DEF TURN_PLAYER_WON   EQU $1
DEF TURN_PLAYER_LOST  EQU $2
DEF TURN_PLAYER_TIED  EQU $3

; wDuelResult constants
DEF DUEL_WIN  EQU $0
DEF DUEL_LOSS EQU $1

; play area location offsets (CARD_LOCATION_* - CARD_LOCATION_PLAY_AREA)
	const_def
	const PLAY_AREA_ACTIVE   ; $0
	const PLAY_AREA_BENCH_1 ; $1
	const PLAY_AREA_BENCH_2 ; $2
	const PLAY_AREA_BENCH_3 ; $3
	const PLAY_AREA_BENCH_4 ; $4
	const PLAY_AREA_BENCH_5 ; $5

; wPlayerDuelVariables or wOpponentDuelVariables constants
RSRESET
DEF DUELVARS_CARD_LOCATIONS                   RB DECK_SIZE
DEF DUELVARS_DECK_CARDS                       RB DECK_SIZE
DEF DUELVARS_PRIZE_CARDS                      RB 6
DEF DUELVARS_NUMBER_OF_CARDS_IN_DECK          RB
DEF DUELVARS_NUMBER_OF_CARDS_IN_HAND          RB
DEF DUELVARS_NUMBER_OF_CARDS_IN_DISCARD_PILE  RB
DEF DUELVARS_NUMBER_OF_POKEMON_IN_PLAY_AREA   RB
DEF DUELVARS_PLAY_AREA                        RB MAX_PLAY_AREA_POKEMON + 1
DEF DUELVARS_ACTIVE EQU DUELVARS_PLAY_AREA + PLAY_AREA_ACTIVE
DEF DUELVARS_BENCH  EQU DUELVARS_PLAY_AREA + PLAY_AREA_BENCH_1
DEF DUELVARS_PLAY_AREA_HP                     RB MAX_PLAY_AREA_POKEMON
DEF DUELVARS_ACTIVE_HP EQU DUELVARS_PLAY_AREA_HP + PLAY_AREA_ACTIVE
DEF DUELVARS_BENCH_HP  EQU DUELVARS_PLAY_AREA_HP + PLAY_AREA_BENCH_1
DEF DUELVARS_PLAY_AREA_STAGE                  RB MAX_PLAY_AREA_POKEMON
DEF DUELVARS_ACTIVE_STAGE EQU DUELVARS_PLAY_AREA_STAGE + PLAY_AREA_ACTIVE
DEF DUELVARS_BENCH_STAGE  EQU DUELVARS_PLAY_AREA_STAGE + PLAY_AREA_BENCH_1
DEF DUELVARS_PLAY_AREA_ATTACHED_DEFENDER      RB MAX_PLAY_AREA_POKEMON
DEF DUELVARS_ACTIVE_ATTACHED_DEFENDER EQU DUELVARS_PLAY_AREA_ATTACHED_DEFENDER + PLAY_AREA_ACTIVE
DEF DUELVARS_BENCH_ATTACHED_DEFENDER  EQU DUELVARS_PLAY_AREA_ATTACHED_DEFENDER + PLAY_AREA_BENCH_1
DEF DUELVARS_PLAY_AREA_ATTACHED_PLUSPOWER     RB MAX_PLAY_AREA_POKEMON
DEF DUELVARS_ACTIVE_ATTACHED_PLUSPOWER EQU DUELVARS_PLAY_AREA_ATTACHED_PLUSPOWER + PLAY_AREA_ACTIVE
DEF DUELVARS_BENCH_ATTACHED_PLUSPOWER  EQU DUELVARS_PLAY_AREA_ATTACHED_PLUSPOWER + PLAY_AREA_BENCH_1
DEF DUELVARS_ACTIVE_CARD_STATUS               RB
DEF DUELVARS_ACTIVE_CARD_FLAGS                RB
DEF DUELVARS_ACTIVE_CARD_SUBSTATUS1           RB
DEF DUELVARS_ACTIVE_CARD_SUBSTATUS2           RB
DEF DUELVARS_ACTIVE_CARD_CHANGED_TYPE         RB
DEF DUELVARS_PRIZES                           RB

; card location constants (DUELVARS_CARD_LOCATIONS)
DEF CARD_LOCATION_DECK         EQU $00
DEF CARD_LOCATION_HAND         EQU $01
DEF CARD_LOCATION_DISCARD_PILE EQU $02
DEF CARD_LOCATION_LOST_ZONE    EQU $03
DEF CARD_LOCATION_PRIZE        EQU $08
DEF CARD_LOCATION_ACTIVE       EQU $10
DEF CARD_LOCATION_BENCH_1      EQU $11
DEF CARD_LOCATION_BENCH_2      EQU $12
DEF CARD_LOCATION_BENCH_3      EQU $13
DEF CARD_LOCATION_BENCH_4      EQU $14
DEF CARD_LOCATION_BENCH_5      EQU $15

; card location flags (DUELVARS_CARD_LOCATIONS)
DEF CARD_LOCATION_PLAY_AREA_F  EQU 4 ; includes active and bench
DEF CARD_LOCATION_PLAY_AREA    EQU 1 << CARD_LOCATION_PLAY_AREA_F
DEF CARD_LOCATION_JUST_DRAWN_F EQU 6
DEF CARD_LOCATION_JUST_DRAWN   EQU 1 << CARD_LOCATION_JUST_DRAWN_F

; status conditions (DUELVARS_ACTIVE_CARD_STATUS)
; two statuses can be combined if they are identified by a different nybble
DEF NO_STATUS       EQU $00
DEF CONFUSED        EQU $01
DEF ASLEEP          EQU $02
DEF PARALYZED       EQU $03
DEF POISONED        EQU $80
DEF DOUBLE_POISONED EQU $c0

DEF DOUBLE_POISONED_F EQU 6
DEF POISONED_F        EQU 7

DEF CNF_SLP_PRZ   EQU $0f ; confused, asleep or paralyzed
DEF PSN_DBLPSN    EQU $f0 ; poisoned or double poisoned
DEF PSN_DAMAGE    EQU 10
DEF DBLPSN_DAMAGE EQU 20

; substatus conditions (DUELVARS_ACTIVE_CARD_SUBSTATUS*)

; *_CHANGED_COLOR constants
DEF HAS_CHANGED_COLOR_F EQU 7
DEF HAS_CHANGED_COLOR   EQU 1 << HAS_CHANGED_COLOR_F

	const_def
	const PRIZES_1 ; $1
	const PRIZES_2 ; $2
	const PRIZES_3 ; $3
	const PRIZES_4 ; $4
	const PRIZES_5 ; $5
	const PRIZES_6 ; $6
