; maximum SCY that can be scrolled in the Duel Scene
DEF MAX_DUEL_SCENE_SCROLL EQU TILEMAP_HEIGHT_PX - SCREEN_HEIGHT_PX

; relevant scroll positions
DEF DUELSCY_OPPONENT_PLAY_AREA EQU  0
DEF DUELSCY_CENTER             EQU 56
DEF DUELSCY_PLAYER_PLAY_AREA   EQU MAX_DUEL_SCENE_SCROLL

; wCardPageNumber constants
DEF CARDPAGE_POKEMON_OVERVIEW    EQU $01
DEF CARDPAGE_POKEMON_ATTACK1_1   EQU $02
DEF CARDPAGE_POKEMON_ATTACK1_2   EQU $03
DEF CARDPAGE_POKEMON_ATTACK2_1   EQU $04
DEF CARDPAGE_POKEMON_ATTACK2_2   EQU $05
DEF CARDPAGE_POKEMON_DESCRIPTION EQU $06
DEF CARDPAGE_ENERGY              EQU $09
DEF CARDPAGE_TRAINER_1           EQU $0d
DEF CARDPAGE_TRAINER_2           EQU $0e

; wAttackPageNumber constants
DEF ATTACKPAGE_ATTACK1_1 EQU $00
DEF ATTACKPAGE_ATTACK1_2 EQU $01
DEF ATTACKPAGE_ATTACK2_1 EQU $02
DEF ATTACKPAGE_ATTACK2_2 EQU $03

; wCardPageType constants
DEF CARDPAGETYPE_NOT_PLAY_AREA EQU $00
DEF CARDPAGETYPE_PLAY_AREA     EQU $01

; card type header constants ($10-tile headers in DuelCardHeaderGraphics)
DEF HEADER_TRAINER EQU $00
DEF HEADER_ENERGY  EQU $01
DEF HEADER_POKEMON EQU $02

; Box message id's
	const_def
	const BOXMSG_PLAYERS_TURN
	const BOXMSG_OPPONENTS_TURN
	const BOXMSG_BETWEEN_TURNS
	const BOXMSG_DECISION
	const BOXMSG_BENCH_POKEMON
	const BOXMSG_ACTIVE_POKEMON
	const BOXMSG_COIN_TOSS

; duel animation constants

; max number of concurrent animations
DEF NUM_DUEL_ANIMS EQU 5

RSRESET
DEF DUELANIM_FLAGS        RB
DEF DUELANIM_DURATION     RB
DEF DUELANIM_OAM_BANK     RB
DEF DUELANIM_OAM_PTR      RW
DEF DUELANIM_FRAMESET_PTR RW
DEF DUELANIM_START_FRAMESET_PTR RW
DEF DUELANIM_YPOS         RB
DEF DUELANIM_XPOS         RB
DEF DUELANIM_TILE_OFFSET  RB
DEF DUELANIM_OBPAL        RB
DEF DUELANIM_STRUCT_SIZE EQU _RS

	const_def
	const DUELANIMF_ACTIVE_F  ; $0
	const DUELANIMF_XFLIP_F   ; $1
	const DUELANIMF_LOOPING_F ; $2

; max number of queued animations
DEF DUEL_ANIMS_QUEUE_CAPACITY EQU 5

RSRESET
DEF DUELANIMENTRY_FLAGS       RB
DEF DUELANIMENTRY_SCY         RB
DEF DUELANIMENTRY_SPRITE_ID   RB
DEF DUELANIMENTRY_ANIM_ID     RB
DEF DUELANIMENTRY_TILE_OFFSET RB
DEF DUELANIMENTRY_STRUCT_SIZE EQU _RS

	const_def
	const DUELANIMENTRYF_CONCURRENT_F ; $0

; duel cursor states
	const_def
	const CURSOR_HIDDEN ; $0
	const CURSOR_IDLE   ; $1
	const CURSOR_POINT  ; $2
	const CURSOR_SNAP   ; $3

DEF CURSOR_PENDING_UPDATE_F EQU 7
DEF CURSOR_PENDING_UPDATE EQU 1 << CURSOR_PENDING_UPDATE_F
