DEF MAX_BENCH_POKEMON     EQU 5
DEF MAX_PLAY_AREA_POKEMON EQU 6 ; arena + bench
DEF MAX_HP                EQU 120
DEF HP_BAR_LENGTH         EQU MAX_HP / 10

DEF STARTING_HAND_SIZE EQU 7

; coin result constants
DEF TAILS EQU 0
DEF HEADS EQU 1

; hWhoseTurn constants
DEF PLAYER_TURN   EQUS "HIGH(wPlayerDuelVariables)"
DEF OPPONENT_TURN EQUS "HIGH(wOpponentDuelVariables)"

; wDuelFinished constants
DEF DUEL_NOT_FINISHED EQU $0
DEF TURN_PLAYER_WON   EQU $1
DEF TURN_PLAYER_LOST  EQU $2
DEF TURN_PLAYER_TIED  EQU $3

; wDuelResult constants
DEF DUEL_WIN  EQU $0
DEF DUEL_LOSS EQU $1

; play area location offsets (CARD_LOCATION_* - CARD_LOCATION_PLAY_AREA)
	const_def
	const PLAY_AREA_ARENA   ; $0
	const PLAY_AREA_BENCH_1 ; $1
	const PLAY_AREA_BENCH_2 ; $2
	const PLAY_AREA_BENCH_3 ; $3
	const PLAY_AREA_BENCH_4 ; $4
	const PLAY_AREA_BENCH_5 ; $5

; wPlayerDuelVariables or wOpponentDuelVariables constants
RSRESET
DEF DUELVARS_CARD_LOCATIONS                   RB DECK_SIZE
DEF DUELVARS_DECK_CARDS                       RB DECK_SIZE
DEF DUELVARS_PRIZE_CARDS                      RB 6
DEF DUELVARS_NUMBER_OF_CARDS_IN_DECK          RB
DEF DUELVARS_NUMBER_OF_CARDS_IN_HAND          RB
DEF DUELVARS_NUMBER_OF_CARDS_IN_DISCARD_PILE  RB
DEF DUELVARS_NUMBER_OF_POKEMON_IN_PLAY_AREA   RB
DEF DUELVARS_PLAY_AREA                        RB MAX_PLAY_AREA_POKEMON + 1
DEF DUELVARS_ARENA EQU DUELVARS_PLAY_AREA + PLAY_AREA_ARENA
DEF DUELVARS_BENCH EQU DUELVARS_PLAY_AREA + PLAY_AREA_BENCH_1
DEF DUELVARS_PLAY_AREA_HP                     RB MAX_PLAY_AREA_POKEMON
DEF DUELVARS_ARENA_HP EQU DUELVARS_PLAY_AREA_HP + PLAY_AREA_ARENA
DEF DUELVARS_BENCH_HP EQU DUELVARS_PLAY_AREA_HP + PLAY_AREA_BENCH_1
DEF DUELVARS_PLAY_AREA_STAGE                  RB MAX_PLAY_AREA_POKEMON
DEF DUELVARS_ARENA_STAGE EQU DUELVARS_PLAY_AREA_STAGE + PLAY_AREA_ARENA
DEF DUELVARS_BENCH_STAGE EQU DUELVARS_PLAY_AREA_STAGE + PLAY_AREA_BENCH_1
DEF DUELVARS_PLAY_AREA_ATTACHED_DEFENDER      RB MAX_PLAY_AREA_POKEMON
DEF DUELVARS_ARENA_ATTACHED_DEFENDER EQU DUELVARS_PLAY_AREA_ATTACHED_DEFENDER + PLAY_AREA_ARENA
DEF DUELVARS_BENCH_ATTACHED_DEFENDER EQU DUELVARS_PLAY_AREA_ATTACHED_DEFENDER + PLAY_AREA_BENCH_1
DEF DUELVARS_PLAY_AREA_ATTACHED_PLUSPOWER     RB MAX_PLAY_AREA_POKEMON
DEF DUELVARS_ARENA_ATTACHED_PLUSPOWER EQU DUELVARS_PLAY_AREA_ATTACHED_PLUSPOWER + PLAY_AREA_ARENA
DEF DUELVARS_BENCH_ATTACHED_PLUSPOWER EQU DUELVARS_PLAY_AREA_ATTACHED_PLUSPOWER + PLAY_AREA_BENCH_1
DEF DUELVARS_ARENA_CARD_STATUS                RB
DEF DUELVARS_ARENA_CARD_FLAGS                 RB
DEF DUELVARS_ARENA_CARD_SUBSTATUS1            RB
DEF DUELVARS_ARENA_CARD_SUBSTATUS2            RB
DEF DUELVARS_ARENA_CARD_CHANGED_TYPE          RB
DEF DUELVARS_PRIZES                           RB

; card location constants (DUELVARS_CARD_LOCATIONS)
DEF CARD_LOCATION_DECK         EQU $00
DEF CARD_LOCATION_HAND         EQU $01
DEF CARD_LOCATION_DISCARD_PILE EQU $02
DEF CARD_LOCATION_LOST_ZONE    EQU $03
DEF CARD_LOCATION_PRIZE        EQU $08
DEF CARD_LOCATION_ARENA        EQU $10
DEF CARD_LOCATION_BENCH_1      EQU $11
DEF CARD_LOCATION_BENCH_2      EQU $12
DEF CARD_LOCATION_BENCH_3      EQU $13
DEF CARD_LOCATION_BENCH_4      EQU $14
DEF CARD_LOCATION_BENCH_5      EQU $15

; card location flags (DUELVARS_CARD_LOCATIONS)
DEF CARD_LOCATION_PLAY_AREA_F  EQU 4 ; includes arena and bench
DEF CARD_LOCATION_PLAY_AREA    EQU 1 << CARD_LOCATION_PLAY_AREA_F
DEF CARD_LOCATION_JUST_DRAWN_F EQU 6
DEF CARD_LOCATION_JUST_DRAWN   EQU 1 << CARD_LOCATION_JUST_DRAWN_F

; status conditions (DUELVARS_ARENA_CARD_STATUS)
; two statuses can be combined if they are identified by a different nybble
DEF NO_STATUS       EQU $00
DEF CONFUSED        EQU $01
DEF ASLEEP          EQU $02
DEF PARALYZED       EQU $03
DEF POISONED        EQU $80
DEF DOUBLE_POISONED EQU $c0


DEF DOUBLE_POISONED_F EQU 6
DEF POISONED_F        EQU 7


DEF CNF_SLP_PRZ   EQU $0f ; confused, asleep or paralyzed
DEF PSN_DBLPSN    EQU $f0 ; poisoned or double poisoned
DEF PSN_DAMAGE    EQU 10
DEF DBLPSN_DAMAGE EQU 20

; substatus conditions (DUELVARS_ARENA_CARD_SUBSTATUS*)

; SUBSTATUS1 are checked on a defending Pokemon
DEF SUBSTATUS1_AGILITY                 EQU $0c
DEF SUBSTATUS1_FLY                     EQU $0d
DEF SUBSTATUS1_PREVENT_LESS_THAN_40    EQU $0e
DEF SUBSTATUS1_NO_DAMAGE_STIFFEN       EQU $0f
DEF SUBSTATUS1_NO_DAMAGE_WITHDRAW      EQU $10
DEF SUBSTATUS1_NO_DAMAGE_HIDE_IN_SHELL EQU $11
DEF SUBSTATUS1_REDUCE_BY_20            EQU $13
DEF SUBSTATUS1_BARRIER                 EQU $14
DEF SUBSTATUS1_HALVE_DAMAGE            EQU $15
DEF SUBSTATUS1_DESTINY_BOND            EQU $16
DEF SUBSTATUS1_NO_DAMAGE_SCRUNCH       EQU $17
DEF SUBSTATUS1_NEXT_TURN_DOUBLE_DAMAGE EQU $19
DEF SUBSTATUS1_REDUCE_BY_10            EQU $1e

; SUBSTATUS2 are checked on an attacking Pokemon
DEF SUBSTATUS2_SMOKESCREEN    EQU $01
DEF SUBSTATUS2_SAND_ATTACK    EQU $02
DEF SUBSTATUS2_REDUCE_BY_20   EQU $03
DEF SUBSTATUS2_AMNESIA        EQU $04
DEF SUBSTATUS2_TAIL_WAG       EQU $05
DEF SUBSTATUS2_LEER           EQU $06
DEF SUBSTATUS2_POUNCE         EQU $07
DEF SUBSTATUS2_CONVERSION2    EQU $08
DEF SUBSTATUS2_ACID           EQU $09
DEF SUBSTATUS2_BONE_ATTACK    EQU $0b
DEF SUBSTATUS2_GROWL          EQU $12

DEF SUBSTATUS3_THIS_TURN_DOUBLE_DAMAGE_F EQU 0
DEF SUBSTATUS3_HEADACHE_F                EQU 1

; DUELVARS_ARENA_CARD_FLAGS constants
DEF USED_PKMN_POWER_THIS_TURN_F EQU 5
DEF USED_LEEK_SLAP_THIS_DUEL_F  EQU 6
DEF CAN_EVOLVE_THIS_TURN_F      EQU 7

DEF USED_PKMN_POWER_THIS_TURN   EQU 1 << USED_PKMN_POWER_THIS_TURN_F
DEF USED_LEEK_SLAP_THIS_DUEL    EQU 1 << USED_LEEK_SLAP_THIS_DUEL_F
DEF CAN_EVOLVE_THIS_TURN        EQU 1 << CAN_EVOLVE_THIS_TURN_F

; DUELVARS_ARENA_CARD_LAST_TURN_EFFECT constants
	const_def
	const LAST_TURN_EFFECT_NONE           ; $00
	const LAST_TURN_EFFECT_DISCARD_ENERGY ; $01
	const LAST_TURN_EFFECT_AMNESIA        ; $02

; *_CHANGED_COLOR constants
DEF HAS_CHANGED_COLOR_F EQU 7
DEF HAS_CHANGED_COLOR   EQU 1 << HAS_CHANGED_COLOR_F

; flag in wDamage + 1 that indicates
; whether damage is unaffected by Weakness/Resistance
DEF UNAFFECTED_BY_WEAKNESS_RESISTANCE_F EQU 7

; effect command constants (TryExecuteEffectCommandFunction)
; ordered by (roughly) execution time
DEF EFFECTCMDTYPE_INITIAL_EFFECT_1         EQU $01
DEF EFFECTCMDTYPE_INITIAL_EFFECT_2         EQU $02
DEF EFFECTCMDTYPE_DISCARD_ENERGY           EQU $06
DEF EFFECTCMDTYPE_REQUIRE_SELECTION        EQU $05
DEF EFFECTCMDTYPE_BEFORE_DAMAGE            EQU $03
DEF EFFECTCMDTYPE_AFTER_DAMAGE             EQU $04
DEF EFFECTCMDTYPE_AI_SELECTION             EQU $08
DEF EFFECTCMDTYPE_AI_SWITCH_DEFENDING_PKMN EQU $0a
DEF EFFECTCMDTYPE_PKMN_POWER_TRIGGER       EQU $07
DEF EFFECTCMDTYPE_AI                       EQU $09

; wDamageEffectiveness constants
DEF WEAKNESS   EQU 1
DEF RESISTANCE EQU 2

; wNoDamageOrEffect constants
DEF NO_DAMAGE_OR_EFFECT_AGILITY      EQU $01
DEF NO_DAMAGE_OR_EFFECT_BARRIER      EQU $02
DEF NO_DAMAGE_OR_EFFECT_FLY          EQU $03
DEF NO_DAMAGE_OR_EFFECT_TRANSPARENCY EQU $04
DEF NO_DAMAGE_OR_EFFECT_NSHIELD      EQU $05

; OppAction_* constants (OppActionTable)
	const_def
	const OPPACTION_PLAY_BASIC_PKMN           ; $00
	const OPPACTION_EVOLVE_PKMN               ; $01
	const OPPACTION_PLAY_ENERGY               ; $02
	const OPPACTION_ATTEMPT_RETREAT           ; $03
	const OPPACTION_FINISH_NO_ATTACK          ; $04
	const OPPACTION_PLAY_TRAINER              ; $05
	const OPPACTION_EXECUTE_TRAINER_EFFECTS   ; $06
	const OPPACTION_BEGIN_ATTACK              ; $07
	const OPPACTION_USE_ATTACK                ; $08
	const OPPACTION_ATTACK_ANIM_AND_DAMAGE    ; $09
	const OPPACTION_DRAW_CARD                 ; $0a
	const OPPACTION_USE_PKMN_POWER            ; $0b
	const OPPACTION_EXECUTE_PKMN_POWER_EFFECT ; $0c
	const OPPACTION_FORCE_SWITCH_ACTIVE       ; $0d
	const OPPACTION_NO_ACTION_0F              ; $0e
	const OPPACTION_NO_ACTION_10              ; $0f
	const OPPACTION_TOSS_COIN_A_TIMES         ; $10
	const OPPACTION_6B30                      ; $11
	const OPPACTION_NO_ACTION_13              ; $12
	const OPPACTION_USE_METRONOME_ATTACK      ; $13
	const OPPACTION_6B15                      ; $14
	const OPPACTION_DUEL_MAIN_SCENE           ; $15
DEF NUM_OPP_ACTIONS EQU const_value

; constants for PracticeDuelActionTable entries
	const_def 1
	const PRACTICEDUEL_DRAW_SEVEN_CARDS
	const PRACTICEDUEL_PLAY_GOLDEEN
	const PRACTICEDUEL_PUT_STARYU_IN_BENCH
	const PRACTICEDUEL_VERIFY_INITIAL_PLAY
	const PRACTICEDUEL_DONE_PUTTING_ON_BENCH
	const PRACTICEDUEL_PRINT_TURN_INSTRUCTIONS
	const PRACTICEDUEL_VERIFY_PLAYER_TURN_ACTIONS
	const PRACTICEDUEL_REPEAT_INSTRUCTIONS
	const PRACTICEDUEL_PLAY_STARYU_FROM_BENCH
	const PRACTICEDUEL_REPLACE_KNOCKED_OUT_POKEMON

; wEffectFailed constants
DEF EFFECT_FAILED_NO_EFFECT    EQU $01
DEF EFFECT_FAILED_UNSUCCESSFUL EQU $02

; wAnimationQueue length
DEF ANIMATION_QUEUE_LENGTH EQU 7

DEF PRIZES_1    EQU $01
DEF PRIZES_2    EQU $02
DEF PRIZES_3    EQU $03
DEF PRIZES_4    EQU $04
DEF PRIZES_5    EQU $05
DEF PRIZES_6    EQU $06

; constants to use as input to LookForCardInDeck
	const_def $80
	const SEARCHEFFECT_POKEMON        ; $80
	const SEARCHEFFECT_NIDORAN        ; $81
	const SEARCHEFFECT_BASIC_FIGHTING ; $82
	const SEARCHEFFECT_BASIC_ENERGY   ; $83
