; maximum SCY that can be scrolled in the Duel Scene
DEF MAX_DUEL_SCENE_SCROLL EQU TILEMAP_HEIGHT_PX - SCREEN_HEIGHT_PX

; relevant scroll positions
DEF DUELSCY_OPPONENT_PLAY_AREA EQU  0
DEF DUELSCY_CENTER             EQU 56
DEF DUELSCY_PLAYER_PLAY_AREA   EQU MAX_DUEL_SCENE_SCROLL

; wCardPageNumber constants
DEF CARDPAGE_POKEMON_OVERVIEW    EQU $01
DEF CARDPAGE_POKEMON_ATTACK1_1   EQU $02
DEF CARDPAGE_POKEMON_ATTACK1_2   EQU $03
DEF CARDPAGE_POKEMON_ATTACK2_1   EQU $04
DEF CARDPAGE_POKEMON_ATTACK2_2   EQU $05
DEF CARDPAGE_POKEMON_DESCRIPTION EQU $06
DEF CARDPAGE_ENERGY              EQU $09
DEF CARDPAGE_TRAINER_1           EQU $0d
DEF CARDPAGE_TRAINER_2           EQU $0e

; wAttackPageNumber constants
DEF ATTACKPAGE_ATTACK1_1 EQU $00
DEF ATTACKPAGE_ATTACK1_2 EQU $01
DEF ATTACKPAGE_ATTACK2_1 EQU $02
DEF ATTACKPAGE_ATTACK2_2 EQU $03

; wCardPageType constants
DEF CARDPAGETYPE_NOT_PLAY_AREA EQU $00
DEF CARDPAGETYPE_PLAY_AREA     EQU $01

; card type header constants ($10-tile headers in DuelCardHeaderGraphics)
DEF HEADER_TRAINER EQU $00
DEF HEADER_ENERGY  EQU $01
DEF HEADER_POKEMON EQU $02

; Box message id's
	const_def
	const BOXMSG_PLAYERS_TURN
	const BOXMSG_OPPONENTS_TURN
	const BOXMSG_BETWEEN_TURNS
	const BOXMSG_DECISION
	const BOXMSG_BENCH_POKEMON
	const BOXMSG_ACTIVE_POKEMON
	const BOXMSG_COIN_TOSS
